plugins:
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'lib/omniauth-spotify.rb'
    - 'tmp/**/*'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'lib/omniauth/strategies/spotify.rb'
    - 'test/rails_integration_test.rb'
    - 'test/omniauth_spotify_test.rb'

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Style/OneClassPerFile:
  Exclude:
    - 'test/rails_integration_test.rb'

Minitest/MultipleAssertions:
  Exclude:
    - 'test/rails_integration_test.rb'
    - 'test/omniauth_spotify_test.rb'
